name: Build and Release FLO APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate Android Folder and Build APK
        run: |
          # 1. تثبيت المكتبات الأساسية
          flutter pub get
          
          # 2. إعادة إنشاء مجلد الـ android والملفات الناقصة للمشروع تلقائياً
          flutter create . --platforms=android
          
          # 3. بناء ملف الـ APK بعد توليد ملفات أندرويد
          flutter build apk --release
          
          # 4. إنشاء مجلد الإخراج ونقل التطبيق إليه
          mkdir -p $GITHUB_WORKSPACE/output-apk
          cp build/app/outputs/flutter-apk/app-release.apk $GITHUB_WORKSPACE/output-apk/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flo-release-apk
          path: output-apk/app-release.apk
